#Remote token services
security.oauth2.resource:
  user-info-uri: http://security/user
  load-balanced: true
  preferTokenInfo: false

logging.level:
  com.netflix.discovery: 'OFF'
  
eureka.instance:
  preferIpAddress: true  
  
ribbon:
  ServerListRefreshInterval: 1000
  
eureka:
  client:
    # Disable the client side behaviour in standalone mode
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
